from __future__ import annotations

from datetime import UTC, datetime
from pathlib import Path

import pytest

from tack import config
from tack.config import ConfigError, LockEntry
from tests.helpers import load, write

WHEN = datetime(2026, 9, 27, 12, 0, 0, tzinfo=UTC)
SHA = "4f1c" + "0" * 36


def test_round_trip(home: Path) -> None:
    paths = load(home).paths
    entries = {
        "cloudflare": LockEntry("https://github.com/cloudflare/skills.git", "main", SHA, WHEN),
        "vercel": LockEntry("https://github.com/vercel-labs/skills.git", None, SHA, WHEN),
        "odd.name": LockEntry("https://example.com/x.git", None, SHA, WHEN),
    }
    assert config.save_lock(paths, entries)
    text = paths.lockfile.read_text()
    assert text.startswith("# Generated by tack. Do not edit; use `tack update`.\nversion = 1\n")
    assert (
        '[source.cloudflare]\ngit = "https://github.com/cloudflare/skills.git"\nref = "main"\n'
        in text
    )
    assert "locked = 2026-09-27T12:00:00Z\n" in text
    assert '[source."odd.name"]' in text
    assert config.load_lock(paths) == entries
    assert not config.save_lock(paths, entries)  # unchanged: not rewritten


def test_no_lockfile(home: Path) -> None:
    assert config.load_lock(load(home).paths) == {}


@pytest.mark.parametrize(
    ("text", "message"),
    [
        ("version = 2\n", "not a version 1 lockfile"),
        ("version = 1\n[source.x]\ngit = 'u'\n", r"\[source.x\] needs git, commit and locked"),
        (
            "version = 1\n[source.x]\ngit = 'u'\ncommit = 'abc'\nlocked = 2026-09-27T12:00:00Z\n",
            "needs git, commit and locked",
        ),
        ("version = 1\n[source\n", "tack.lock"),
    ],
)
def test_bad_lockfile(home: Path, text: str, message: str) -> None:
    paths = load(home).paths
    write(paths.lockfile, text)
    with pytest.raises(ConfigError, match=message):
        config.load_lock(paths)


def test_lock_entry_matches(home: Path) -> None:
    cfg = load(home, '[[source]]\nname = "x"\ngit = "https://e.com/x.git"\nref = "main"\n')
    (src,) = cfg.sources
    assert LockEntry("https://e.com/x.git", "main", SHA, WHEN).matches(src)
    assert not LockEntry("https://e.com/x.git", None, SHA, WHEN).matches(src)
    assert not LockEntry("https://e.com/y.git", "main", SHA, WHEN).matches(src)


def test_after_save(home: Path) -> None:
    out = home / "saved.txt"
    cfg = load(home, f"after_save = \"printf '%s' {{path}} > {out}\"\n")
    target = home / "dir with space" / "tack.lock"
    assert config.run_after_save(cfg, target) is None
    assert out.read_text() == str(target)

    cfg = load(home, 'after_save = "echo nope >&2; exit 3"\n')
    assert config.run_after_save(cfg, target) == "after_save `echo nope >&2; exit 3` exited 3: nope"
    assert config.run_after_save(load(home, ""), target) is None
